name: tasse_forfettario
description: Calcolatore tasse per regime forfettario

publish_to: "none"

version: 1.1.3+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  awesome_flutter_extensions: ^0.0.1+2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_hooks: ^0.18.0
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^2.0.0-dev.9
  url_launcher: ^6.1.4

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
